BATCH_SIZE: 16
HEIGHT: 150
STRIDE: 128
WIDTH: 150
add_activ_14reso: 1
add_activ_enforce_nonnegative: 1
add_activ_flatten: 0
add_activ_loss_descend: 0
add_activ_round_clip_inner_pred: 1
add_activ_round_clip_pred: 1
add_chm: 0
add_input2: 0
add_output_names:
- B_frac
- C_frac
add_outputs: 0
add_seg: 0
augmentation_prob: 0.5
band_select: 1
beta1: 0.5
beta2: 0.999
chm_pred: 0
chm_resample: 0
dropoutchm: 10
downsample: 0
downsample_ratio: 2
imageNetnorm: 1
img_ch: 3
input2_name: ''
input_chm_dir: null
input_chm_pref: null
input_image_dir: /home/sizhuo/Downloads/test_preds/test_images
input_image_pref: '2018'
input_image_type: .tif
inputlength: 224
keep_all_features: 0
lr: 0
lr_decay_frequency: 0
lr_decay_rate: 0
meanstdnorm: 0
min_lr: 0
mode: inference
model_path: /home/sizhuo/Desktop/code_repository/CNN_AGB/saved_models/old_data_new_train/rgb_recap/AGB_20230419-1123-torchEfficientnetb0_map-Epo300-yearAft_2015-patch_224-Loss_L1-bands_RGB-_new_rgb_models_relu_enforce_nonnegative/bestR2.pt
model_type: torchEfficientnetb0_map
new_bands:
- 0
- 1
- 2
nnlevel: 4
num_epochs: 0
num_workers: 1
operator: MAX
output_act_suffix: AGB_activation
output_activation: 1
output_activation_dim: 14
output_ch: 1
output_dir: /home/sizhuo/Downloads/test_preds/test_images/results/
output_dtype: float32
output_image_type: .tif
output_suffix: _AGB
pretrained: 1
refine_seg: 0
rescale_output: 0
sum_output: 1
t: 3
task: regression
upscale: 1
weightDecay: 0.1
