add_activ_14reso: 0
add_activ_enforce_nonnegative: 1
add_activ_flatten: 0
add_activ_loss_descend: 0
add_activ_round_clip_inner_pred: 1
add_activ_round_clip_pred: 1
add_chm: 0
add_chmInput: 0
add_exgi: 0
add_input2: 0
add_ndvi: 0
add_output_names:
- B_frac
- C_frac
add_outputs: 0
add_seg: 0
attri_id: psussu
attri_label: BMag_ha
attri_year: year
augmentation_prob: 0.5
batch_size: 32
beta1: 0.5
beta2: 0.999
checkpoint_dir: /home/sizhuo/Desktop/code_repository/CNN_AGB/checkpoints
chm_buffercrop: 0
chm_pred: 0
chm_resample: 0
circle_crop: 1
classification_label_fn: null
conf_score: 1
conf_score_valid: 1
correction_score: 1
cropInnerLength: 150
cropRandomSquare: 0
croplength: 180
dk: 1
downsample: 0
downsample_ratio: 0
dropoutchannel: 0
dropoutchm: 10
earlystop: 0
equalize_img: 0
expandGray: 0
imageCallbackDir: /home/sizhuo/Desktop/code_repository/CNN_AGB/visionCallbacks
imageNetnorm: 1
image_callback_freq: 20
image_size: 200
img_ch: 3
input2_name: ''
inputlength: 224
keep_all_features: 0
log_activation_map: 0
log_step: 2
loss_alpha: 200
loss_func: L1
loss_func_addop: BCElog
loss_name: MAE
loss_weight_high: 0
lr: 0.0005
lr_decay_frequency: 100
lr_decay_rate: 0.9
meanstdnorm: 0
mergeTrainValid: 0
min_lr: 1.0e-05
mode: train
model_path: /home/sizhuo/Desktop/code_repository/CNN_AGB/saved_models/test/
model_suf: None
model_type: torchEfficientnetb1_map
nir_rep_red: 0
nnlevel: 4
norm_wei: 1
num_epochs: 300
num_workers: 1
onlyRGB: 1
output_ch: 1
planet_data: 0
pretrained: 1
refine_seg: 0
result_path: /home/sizhuo/Desktop/code_repository/CNN_AGB/result/
resume_train: 0
rgb2gray: 0
saveImages: 0
score_name: score
showmap: 0
split_ratio: 0.8
subsample_data: 0
subsample_data_rat: 0
t: 3
task: regression
tensorboard:
  log: false
test_chm_path: None
test_forestOnly: 1
test_forestThres: 0.5
test_path: /home/sizhuo/Desktop/code_repository/CNN_AGB/dataset/test2/
test_seg_path: None
test_type_separate: 0
test_vis: 0
test_weight_name: forest_frac
test_year_end: 2018
test_year_start: 2015
train_chm_path: None
train_path: /home/sizhuo/Desktop/code_repository/CNN_AGB/dataset/train/
train_seg_path: None
use_color: 1
val_step: 2
valid_chm_path: None
valid_path: /home/sizhuo/Desktop/code_repository/CNN_AGB/dataset/valid2/
valid_seg_path: None
wandb:
  log: true
  name: ${model_type}
  project: biomass
  public: true
weightDecay: 0.1
weight_forest_yesno: 1
weight_name: weight
year: 2015.0
year_end: 2018.0
